### ISSUE TITLE
رزومه مجید آقا امینی

### ISSUE THREAD

**Issue by majid-am** [AliRazavi-edu/PNU_3991#142]
سلام استاد
https://github.com/majid-am
https://github.com/majid-am/PNU_3991/blob/main/cert-1024-20593691.jpg
مجید آقا امینی 
شماره تماس 09352000904
شغل : کارمند 
وضعیت تاهل: متاهل

**Comment by saharzeinivand** [comment]
سلام چرا اطلاعات رو در ایشو قرار دادین.لطفا در واتساپ به من پیام بدین.زینی وند
