### ISSUE TITLE
رزومه نادر سیفی

### ISSUE THREAD

**Issue by naderseifi** [AliRazavi-edu/PNU_3991#8]
<table style="float: right; height: 206px;" width="794">
<tbody>
<tr>
<td style="width: 784px;">
<p style="text-align: center;"><strong><span style="color: #ff0000;">اطلاعات شخصي</span></strong></p>
</td>
</tr>
<tr>
<td style="width: 784px;">
<p style="text-align: center;"><strong>نام : &nbsp;نادر&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; شماره تماس :&nbsp; 09183132208</strong></p>
<p style="text-align: center;"><strong>نام خانوادگي :&nbsp; سیفی </strong></p>
<p style="text-align: center;"><strong>پست الکترونيکي :&nbsp; </strong><strong><a href="mailto:seyfi@umsha.ac.ir">seyfi@umsha.ac.ir</a> <br /></strong></p>
<p style="text-align: center;"><strong>تاريخ تولد : 1356&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;وضعيت نظام وظيفه: گذارنده شده</strong></p>
<p style="text-align: center;"><strong>کد ملی : 0061712515&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; واتساپ : 09393132208</strong></p>
<p><strong>&nbsp;</strong></p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<table style="width: 684px;">
<tbody>
<tr>
<td style="text-align: right; width: 674px;">
<p style="text-align: center;"><span style="text-decoration: underline;"><strong><span style="color: #ff0000; text-decoration: underline;">سوابق علمي و آموزشي</span></strong></span></p>
</td>
</tr>
<tr>
<td style="text-align: right; width: 674px;">
<p><span style="color: #ff0000;"><strong><u>&nbsp;</u></strong><strong><u>تحصيلات <br /></u></strong></span></p>
<p>&nbsp;</p>
<table>
<tbody>
<tr>
<td width="105">
<p><strong>مقطع</strong></p>
</td>
<td width="134">
<p><strong>رشته</strong></p>
</td>
<td width="163">
<p><strong>گرايش</strong></p>
</td>
<td width="120">
<p><strong>دانشگاه</strong></p>
</td>
<td width="53">
<p><strong>شروع</strong></p>
</td>
<td width="52">
<p><strong>اتمام</strong></p>
</td>
</tr>
<tr>
<td width="105">
<p><strong>کاردانی</strong></p>
</td>
<td width="134">
<p><strong>مدیریت اطلاعات سلامت </strong></p>
</td>
<td width="163">
<h4>علوم پزشکی</h4>
</td>
<td width="120">
<p><strong>دانشگاه علوم پزشکی تهران</strong></p>
</td>
<td width="53">
<p><strong>1374</strong></p>
</td>
<td width="52">
<p><strong>1377</strong></p>
</td>
</tr>
<tr>
<td width="105">
<p><strong>كارشناسي</strong></p>
</td>
<td width="134">
<p><strong>مدیریت اطلاعات سلامت</strong></p>
</td>
<td width="163">
<h4>علوم پزشکی</h4>
</td>
<td width="120">
<p><strong>دانشگاه علوم پزشکی تهران</strong></p>
</td>
<td width="53">
<p><strong>1377</strong></p>
</td>
<td width="52">
<p><strong>1380</strong></p>
</td>
</tr>
<tr>
<td width="105">
<p><strong>کارشناسي ارشد</strong></p>
</td>
<td width="134">
<p><strong>مهندسی نرم افزار</strong></p>
</td>
<td width="163">
<p><strong>مهندسی</strong></p>
</td>
<td width="120">
<p><strong>بین المللی اربیل عراق</strong></p>
</td>
<td width="53">
<p><strong>1395</strong></p>
</td>
<td width="52">
<p><strong>1399</strong></p>
</td>
</tr>
</tbody>
</table>
<p><strong>&nbsp;</strong></p>
<p><span style="color: #ff0000;"><strong>&nbsp;&nbsp;&nbsp; </strong></span><strong><u><span style="color: #ff0000;">سوابق کاری</span> :</u></strong></p>
<ul>
<li><strong>مسئول آمار و مدیریت اطلاعات سلامت &nbsp;بیمارستان امیر المومنین اسدآباد 1380-1382</strong></li>
<li><strong>مسئول مدارک پزشکی بیمارستان 557 ارتش&nbsp; 1382-1383</strong></li>
<li><strong>کارشناس </strong><strong>HSE</strong><strong> شرکت عملیات اکتشاف نفت 1383-1384</strong></li>
<li><strong>مدیر مناطق عملیاتی حفاری مارون و دشت آزادگان جنوب 1384-1385</strong></li>
<li><strong>مسئول مدیریت اطلاعات سلامت &nbsp;بیمارستان اکباتان همدان &nbsp;1385-1394</strong></li>
<li><strong>مسئول مدیریت اطلاعات سلامت بیمارستان صحرائی ابن سینا1390-1394</strong></li>
<li><strong>مسئول اعتبار بخشی بیمارستان اکباتان 1390-1393</strong></li>
<li><strong>مدیر وب سایت بیمارستان اکباتان 1386-1394</strong></li>
<li><strong>مدرس مدیریت وب سایت بیمارستانهای زیر مجموعه علوم پزشکی همدان 1387-1392</strong></li>
<li><strong>مسئول روابط عمومی بیمارستان اکباتان 1392-1394</strong></li>
<li><strong>عضو تیم مدیریت اجرائی بیمارستان اکباتان 1390-1393</strong></li>
<li><strong>کارشناس فناوری اطلاعات معاونت درمان دانشگاه 1396-1398</strong></li>
<li><strong>مسئول مدیریت اطلاعات سلامت بیمارستان قلب فرشچیان 1394- تا کنون</strong></li>
<li><strong>مسئول گردشگری سلامت بیمارستان قلب فرشچیان 1395- تا کنون</strong></li>
<li><strong>مدیریت وب سایت انگلیسی بیمارستان قلب 1397-تا کنون</strong></li>
<li><strong>کارشناس مسئول فناوری اطلاعات سلامت بیمارستان فوق تخصصی قلب و عروق فرشچیان 1398 تاکنون </strong></li>
<li><strong>عضو ستاد کرونا و رابط آمار و اطلاعات با وزارت بهداشت بیمارستان قلب و عروق </strong></li>
</ul>
<p>&nbsp;</p>
<p><strong><u><span style="color: #ff0000;">دوره هاي آموزشي شغلی</span>:</u></strong></p>
<ul>
<li><strong>آموزش ضمن خدمت به مدت 2300 ساعت</strong></li>
<li><strong>تدریس در زمینه شغلی به صورت کلاس دانشگاهی به مدت 121 ساعت </strong></li>
<li><strong>مربی دانشجویان کارشناسی مدیریت اطلاعات سلامت در بیمارستان و طی دوره کارآموزی ایشان </strong></li>
<li><strong>عضو گروه آموزشی دانشکده پیراپزشکی علوم پزشکی همدان </strong></li>
</ul>
</td>
</tr>
<tr>
<td style="width: 674px;">
<p style="text-align: center;"><strong><span style="color: #ff0000;">مهارت ها و توانايي ها</span></strong></p>
</td>
</tr>
<tr>
<td style="width: 674px;">
<p style="text-align: right;"><strong>&nbsp;</strong></p>
<p style="text-align: right;"><span style="color: #ff0000;"><strong><u>مهارت&nbsp; و تجارب </u></strong></span></p>
<p style="text-align: right;"><strong>&nbsp;</strong></p>
<ul style="text-align: right;">
<li><strong>Microsoft Excel </strong><strong>)</strong><strong>professional</strong> <strong>(</strong></li>
<li><strong>Word, Excel, PowerPoint </strong><strong>)</strong><strong>Office</strong><strong>(</strong></li>
<li><strong>Access</strong></li>
<li><strong>MS Project, primavera</strong></li>
<li><strong>Q basic</strong></li>
<li><strong>Photoshop</strong></li>
<li><strong>سیستم های اطلاعات بیمارستانی</strong></li>
<li><strong>برنامه نویسی سایت</strong></li>
<li><strong>طراحی سایت</strong></li>
<li><strong>Spss</strong></li>
</ul>
<p style="text-align: right;"><strong>&nbsp;</strong></p>
<p style="text-align: right;"><strong><u><span style="color: #ff0000;">زبان خارجي</span> <br /></u></strong></p>
<p style="text-align: right;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><strong>زبان انگليسي </strong><strong>&ndash;</strong><strong> عربی-ترکی در سطح فهمیدن </strong></p>
<p style="text-align: right;">&nbsp;</p>
<p style="text-align: right;">&nbsp;</p>
<p style="text-align: right;"><strong><u><span style="color: #ff0000;">تدريس</span> <br /></u></strong></p>
<p style="text-align: right;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><strong>طراحی وب سایت</strong></p>
<p style="text-align: right;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><strong>مدیریت وب سایت</strong></p>
<p style="text-align: right;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><strong>فتوشاپ</strong></p>
<p style="text-align: right;"><strong>&nbsp;&nbsp; </strong><strong>MS DOS</strong></p>
<p style="text-align: right;"><strong>&nbsp;</strong><strong>عنوان و مهارت های شغلی </strong></p>
<p><strong>&nbsp;</strong></p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>

**Comment by saharzeinivand** [comment]
سلام.چرا رزومتون رو داخل ایشو قرار دادین؟رزومه رو درگیتهاب خودتون باید قرار بدین

**Comment by naderseifi** [comment]
سلام و عرض ادب خدمت شما خانم زيني وند 
آيا امكان cut 
كردن اطلاعات از اينجا به گيتاژ خودم وجود دارد؟

**Comment by saharzeinivand** [comment]
سلام واتساپ پیام بدین تا راهنمایی کنم

در تاریخ دوشنبه ۲۸ دسامبر ۲۰۲۰،‏ ۱۱:۴۹ nader seifi <notifications@github.com>
نوشت:

**Comment by naderseifi** [comment]
ببخشيد شماره واتساپ 
را لطف ميكنيد ؟

**Comment by saharzeinivand** [comment]
09187451719

در تاریخ دوشنبه ۲۸ دسامبر ۲۰۲۰،‏ ۱۲:۰۷ nader seifi <notifications@github.com>
نوشت:

**Comment by saharzeinivand** [comment]
09187451710
ببخشید این درسته

در تاریخ دوشنبه ۲۸ دسامبر ۲۰۲۰،‏ ۱۲:۳۷ sahar zeinivand <
sahar.zeinivand95@gmail.com> نوشت:
