### ISSUE TITLE
رزومه رضا خسروی

### ISSUE THREAD

**Issue by rezakhosravisalary** [AliRazavi-edu/PNU_3991#85]

**Comment by rezakhosravisalary** [comment]
[رزومه رضا خسروی.pdf](https://github.com/AliRazavi-edu/PNU_3991/files/5611081/default.pdf)

**Comment by saharzeinivand** [comment]
سلام رزومتون رو باید در گیتهاب خودتون قرار بدین ولینکش رو در دایرکتوری درستون در بخش ردیف خودتون قرار بدین

**Comment by rezakhosravisalary** [comment]
سلام ممنونم
