### ISSUE TITLE
رزومه محمد عابدی

### ISSUE THREAD

**Issue by Abedi12** [AliRazavi-edu/PNU_3991#98]
[رزومه جنریتور محمد عابدی.pdf](https://github.com/AliRazavi-edu/PNU_3991/files/5648961/default.pdf)

**Comment by saharzeinivand** [comment]
سلام.رزومتون رو در گیتاب خودتون باید قرار بدین وبعدش لینکش رو در دایرکتوری درستون در بخش ردیف خودتون قرار بدین
